apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-db-produto-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-db-produto-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-db-produto
  template:
    metadata:
      labels:
        app: tech-challenge-db-produto
    spec:
      containers:
        - name: sql-db-container
          image: mysql:8.1
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: mysql_produto_db_name
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: mysql_produto_db_username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: mysql_produto_db_password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fiap-tech-secrets
                  key: mysql_produto_db_root_password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: tech-challenge-db-produto-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: tech-challenge-db-produto-persistent-storage
          persistentVolumeClaim:
            claimName: tech-challenge-db-produto-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-db-produto-svc
spec:
  selector:
    app: tech-challenge-db-produto
  ports:
    - protocol: TCP
      port: 3306
