apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tech-challenge-mongo-producao-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-mongo-producao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tech-challenge-mongo-producao
  template:
    metadata:
      labels:
        app: tech-challenge-mongo-producao
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mongo_producao_username
                  name: fiap-tech-secrets
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongo_producao_password
                  name: fiap-tech-secrets
          image: mongo:latest
          name: mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - mountPath: /data/db
              name: tech-challenge-mongo-persistent-storage
      volumes:
        - name: tech-challenge-mongo-persistent-storage
          persistentVolumeClaim:
            claimName: tech-challenge-mongo-producao-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-mongo-producao-svc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: tech-challenge-mongo-producao
  type: ClusterIP
